export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = "REGISTER_FAIL"
export const USER_FOUND = "USER_FOUND"
export const UNAUTHRIZED = "UNAUTHRIZED"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"